version: "3.9"
services:

  postgres_db:
    image: adv-db/postgres
    ports:
      - "5432:5432"
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=password
  
  postgres_client:
    image: adv-db/clients
    network_mode: "host"
    command: psql -h localhost -U postgres postgres
  
  general_client:
    image: adv-db/clients
    network_mode: "host"
    volumes:
      - "C:/Users/Ben/Repositories/csci-540:/mount"
      
  hbase_db:
    image: adv-db/hbase
    network_mode: "host"
    ports:
      - "8080:8080"
    volumes:
      - "C:/Users/Ben/Repositories/csci-540/homework_2:/mnt"

  mongo_db:
    image: adv-db/mongo
    network_mode: "host"
    ports:
      - "27017:27017"

  mongo_client:
    image: adv-db/clients
    network_mode: "host"
    volumes:
      - "C:/Users/Ben/Repositories/csci-540:/mnt"
    command: mongo my-advdb-database
    
  mongo_hw3:
    image: adv-db/clients
    network_mode: "host"
    volumes:
      - "C:/Users/Ben/Repositories/csci-540/homework_3/mnt:/mnt"
    command: bash /mnt/import

  redis_db:
    image: adv-db/redis
    network_mode: "host"
    ports:
      - "6379:6379"
      
  redis_client:
    image: adv-db/clients
    network_mode: "host"
    volumes:
      - "C:/Users/Ben/Repositories/csci-540:/mnt"
    command: redis-cli